version: '3.8'

services:
  # The Backend Service (Node.js/Express API)
  backend:
    build: ./backend
    container_name: backend_app
    restart: always
    # No ports need to be exposed to the outside world,
    # as only the frontend container needs to talk to it.

  # The Frontend Service (React App)
  frontend:
    build: ./frontend
    container_name: frontend_app
    restart: always
    ports:
      # Map port 80 of the EC2 instance to port 80 of the container.
      # The Nginx server inside the container listens on port 80 by default.
      - "80:80"
    depends_on:
      # This ensures the backend container starts before the frontend.
      - backend

